#!/usr/bin/env zsh
# dotfiles/.functions/git-clean

function git-clean {

  # Run git garbage collection in all my git repos

  declare -a dirs
  local repo_name

  while IFS=$'\n' read -r dir; do 
    dirs+=("${dir}"); 
  done < <(find "$HOME" -type d -maxdepth 4)

  echo "[♻️] Garbage Collecting in Git Repos..."
  
  for dir in "${dirs[@]}"; do
    ( # SUBSHELL
      cd "${dir}" || exit
      if [ -d .git ]; then
        repo_name=$(basename "${dir}")
        echo "  Cleaning: ${BOLD}${repo_name}${RESET}"
        git gc --aggressive --quiet >/dev/null
        # git fsck --full >/dev/null 2>&1
      fi
    )
  done  
}

git-clean

