#!/usr/bin/env zsh
# dotfiles/.functions/git-clean

function git-clean {

  # Run git garbage collection in all my git repos

  echo "[♻️] Garbage Collecting in Git Repos..."

  while IFS=$'\n' read -r dir; do
    dir="${dir%/.git}"
    (
      cd "${dir}" || exit
      local repo_name
      repo_name=$(basename "${dir}")
      echo "  Cleaning: ${repo_name}"
      GIT_TERMINAL_PROMPT=0 git fetch --prune &>/dev/null
      git gc --quiet
      git fsck --full --strict &>/dev/null
    )
  done < <(find "$HOME/Documents/Projects" -type d -maxdepth 5 -name .git)
}
