#!/usr/bin/env zsh
# dotfiles/.functions/stouch

function stouch {

if [[ ! -x "$HOME/Documents/Projects/dotfiles/bitterswet" ]]; then
  echo "[❌] '~/Documents/Projects/dotfiles/bitterswet' NOT executable"
  return 1
fi

"$HOME/Documents/Projects/dotfiles/bittersweet" "sudotouch"
}

stouch

