#!/usr/bin/env zsh
# dotfiles/.functions/update!

function update! {
  # update! 
  #   Update Homebrew, LaTeX packages and macOS 
  #   Preferred way to check if a bianry exsists and is exectuable is
  #     if [ -x "$(command -v $BINARY)" ]; then
  #     See: https://stackoverflow.com/a/677212
  #     See also: https://unix.stackexchange.com/a/85250

  echo "[⚠️ ] Updating brew, tlmgr & macOS..."
  sudo -v

  if [ -x "$(command -v brew)" ]; then
    echo "[🍺] brew..."
    brew update
    brew upgrade
    brew cleanup
    brew autoremove
    brew doctor
  fi

  if [ -x "$(command -v tlmgr)" ]; then
    echo "[📝] LaTeX..."
    sudo tlmgr update --self
    sudo tlmgr update –all
  fi

  if [ -x "$(command -v softwareupdate)" ]; then
    echo "[🍎] macOS..."
    softwareupdate -i -a
  fi
}

update!

