#!/usr/bin/env zsh
# dotfiles/.functions/update!

function update! {
  # update! 
  #   Update Homebrew, LaTeX packages and macOS 
  #   Preferred way to check if a bianry exsists and is exectuable is
  #     if [ -x "$(command -v $BINARY)" ]; then
  #     See: https://stackoverflow.com/a/677212
  #     See also: https://unix.stackexchange.com/a/85250

  echo "[⚠️ ] Updating Stuff..."
  sudo -v

  if [ -x "/usr/local/bin/brew" ]; then
    
    echo "[🍺] brew..."
    
    if ! brew_output=$(brew update); then
      echo "${brew_output}"
    fi
    
    if ! brew_output=$(brew upgrade); then
      echo "${brew_output}"
    fi

    if ! brew_output=$(brew cleanup); then
      echo "${brew_output}"
    fi

    # brew file init -y
  fi

  if [ -x "$(command -v tlmgr)" ]; then
    echo "[📝] LaTeX..."
    sudo tlmgr update --self
    sudo tlmgr update –all
  fi

  if [ -x "$(command -v pip3)" ]; then
    echo "[🐍] pip3..."
    pip3 install --upgrade pip
  fi

  if [ -x "/usr/local/opt/ruby/bin/gem" ]; then
    echo "[💎] Ruby Gems...🥲"
    gem update
    gem cleanup
  fi


  if [ -x /usr/local/bin/mas ]; then
    echo "[💻] App Store Apps..."
    mas upgrade
  fi


  if [ -x "$(command -v softwareupdate)" ]; then
    echo "[🍎] macOS..."
    softwareupdate -i -a
  fi
}

update!

