#!/usr/bin/env zsh
# dotfiles/.functions/update!

function update! {

  # Update Homebrew, LaTeX packages and macOS

  echo "[⚠️ ] Updating Stuff..."
  sudo -v

  if [ -x "/usr/local/bin/brew" ]; then
    echo "[🍺] brew..."
    brew update
    brew upgrade
    brew cleanup
    brew file init -y 
  fi

  if [ -x "$(command -v tlmgr)" ]; then
    echo "[📝] LaTeX..."
    sudo tlmgr update --self
    sudo tlmgr update –all
  fi

  if [ -x "$(command -v pip3)" ]; then
    echo "[🐍] pip3..."
    pip3 install --upgrade pip
  fi

  if [ -x "/usr/local/opt/ruby/bin/gem" ]; then
    echo "[💎] Ruby Gems...🥲"
    gem update
    gem cleanup
  fi

  if [[ "${OS}" == "Darwin" ]]; then
    
    if [ -x /usr/local/bin/mas ]; then
      echo "[💻] App Store Apps..."
      mas upgrade
    fi

    echo "[🍎] macOS..."
    softwareupdate -i -a
  fi

  if [[ "${OS}" == "Linux" ]]; then
    echo "[🐧] Linux..."
    if [ -x "$(command -v apt-get)" ]; then
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get autoclean -y
      sudo apt-get autoremove -y
    
    elif [ -x "$(command -v yum)" ]; then
      sudo yum update
    fi
  fi
}

update!

