name: Shellcheck 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  analyse:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      
    - name: Get Shellcheck
      run: |
        curl -sL https://github.com/koalaman/shellcheck/releases/download/v0.9.0/shellcheck-v0.9.0.darwin.x86_64.tar.xz -o shellcheck-v0.9.0.tar.xz
        tar -xf shellcheck-v0.9.0.tar.xz

    # Runs a set of commands using the runners shell
    - name: Execute test
      env:
        TERM: xterm-256color
        PATH: $PATH:shellcheck-v0.9.0/
      run: ./test
