name: Shellcheck 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  analyse:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    
    - name: Download Shellcheck
      run: |
        SHELLCEHCK_LATEST_VERSION="$(curl -I https://github.com/koalaman/shellcheck/releases/latest \
                                    | awk '/^location: / {split($2, array, "/"); version=array[length(array)]; sub(/^v/, "", version); print version}')"
        
        curl --silent --location --output  "${{ github.workspace }}/shellcheck-v${SHELLCEHCK_LATEST_VERSION}.tar.xz" \
        https://github.com/koalaman/shellcheck/releases/download/v${SHELLCEHCK_LATEST_VERSION}/shellcheck-v${SHELLCEHCK_LATEST_VERSION}.darwin.x86_64.tar.xz

        tar -xf "${{ github.workspace }}/shellcheck-v${SHELLCEHCK_LATEST_VERSION}.tar.xz"
        mv "${{ github.workspace }}/shellcheck-v${SHELLCEHCK_LATEST_VERSION}/shellcheck" \
            "${{ github.workspace }}/shellcheck"

    # Runs a set of commands using the runners shell
    - name: Execute test
      env:
        TERM: xterm-256color
        PATH: $PATH:${{ github.workspace }}/shellcheck
      run: ./test
